package com.today36524.api.user.response;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 分页查询用户返回体

        **/
        public class FindUsersByPageResponse{
        
            /**
            *
            **/
            public com.today36524.api.common.domain.PageResponse pageResponse ;
            public com.today36524.api.common.domain.PageResponse getPageResponse(){ return this.pageResponse; }
            public void setPageResponse(com.today36524.api.common.domain.PageResponse pageResponse){ this.pageResponse = pageResponse; }

            public com.today36524.api.common.domain.PageResponse pageResponse(){ return this.pageResponse; }
            public FindUsersByPageResponse pageResponse(com.today36524.api.common.domain.PageResponse pageResponse){ this.pageResponse = pageResponse; return this; }
          
            /**
            *
            **/
            public java.util.List<com.today36524.api.user.response.GetUserResponse> results = new java.util.ArrayList();
            public java.util.List<com.today36524.api.user.response.GetUserResponse> getResults(){ return this.results; }
            public void setResults(java.util.List<com.today36524.api.user.response.GetUserResponse> results){ this.results = results; }

            public java.util.List<com.today36524.api.user.response.GetUserResponse> results(){ return this.results; }
            public FindUsersByPageResponse results(java.util.List<com.today36524.api.user.response.GetUserResponse> results){ this.results = results; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageResponse").append("\":").append(this.pageResponse.toString()).append(",");
    stringBuilder.append("\"").append("results").append("\":").append(this.results).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      