package com.today36524.api.user.response;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 获取单个用户sql返回体

        **/
        public class GetUserSqlResponse{
        
            /**
            *
            **/
            public String userName ;
            public String getUserName(){ return this.userName; }
            public void setUserName(String userName){ this.userName = userName; }

            public String userName(){ return this.userName; }
            public GetUserSqlResponse userName(String userName){ this.userName = userName; return this; }
          
            /**
            *
            **/
            public String telephone ;
            public String getTelephone(){ return this.telephone; }
            public void setTelephone(String telephone){ this.telephone = telephone; }

            public String telephone(){ return this.telephone; }
            public GetUserSqlResponse telephone(String telephone){ this.telephone = telephone; return this; }
          
            /**
            *
            **/
            public String email ;
            public String getEmail(){ return this.email; }
            public void setEmail(String email){ this.email = email; }

            public String email(){ return this.email; }
            public GetUserSqlResponse email(String email){ this.email = email; return this; }
          
            /**
            *
            **/
            public String qq ;
            public String getQq(){ return this.qq; }
            public void setQq(String qq){ this.qq = qq; }

            public String qq(){ return this.qq; }
            public GetUserSqlResponse qq(String qq){ this.qq = qq; return this; }
          
            /**
            *
            **/
            public int status ;
            public int getStatus(){ return this.status; }
            public void setStatus(int status){ this.status = status; }

            public int status(){ return this.status; }
            public GetUserSqlResponse status(int status){ this.status = status; return this; }
          
            /**
            *
            **/
            public int integral ;
            public int getIntegral(){ return this.integral; }
            public void setIntegral(int integral){ this.integral = integral; }

            public int integral(){ return this.integral; }
            public GetUserSqlResponse integral(int integral){ this.integral = integral; return this; }
          
            /**
            *
            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public GetUserSqlResponse createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          
            /**
            *
            **/
            public long updatedAt ;
            public long getUpdatedAt(){ return this.updatedAt; }
            public void setUpdatedAt(long updatedAt){ this.updatedAt = updatedAt; }

            public long updatedAt(){ return this.updatedAt; }
            public GetUserSqlResponse updatedAt(long updatedAt){ this.updatedAt = updatedAt; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("userName").append("\":\"").append(this.userName).append("\",");
    stringBuilder.append("\"").append("telephone").append("\":\"").append(this.telephone).append("\",");
    stringBuilder.append("\"").append("email").append("\":\"").append(this.email).append("\",");
    stringBuilder.append("\"").append("qq").append("\":\"").append(this.qq).append("\",");
    stringBuilder.append("\"").append("status").append("\":").append(this.status).append(",");
    stringBuilder.append("\"").append("integral").append("\":").append(this.integral).append(",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    stringBuilder.append("\"").append("updatedAt").append("\":").append(this.updatedAt).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      