package com.today36524.api.user.scala.enums;

      class UserCountryPhonePrefix private(val id: Int, val name: String) extends com.github.dapeng.core.enums.TEnum(id,name) {}

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      * 

 会员用户所在国家区域电话号码前缀

      **/
      object UserCountryPhonePrefix {

      
            val CN = new UserCountryPhonePrefix(86,"")
          
            val JP = new UserCountryPhonePrefix(81,"")
          
            val KR = new UserCountryPhonePrefix(82,"")
          
            val US = new UserCountryPhonePrefix(1,"")
          
            val UK = new UserCountryPhonePrefix(44,"")
          
      val UNDEFINED = new UserCountryPhonePrefix(-1,"UNDEFINED") // undefined enum
      

      def findByValue(v: Int): UserCountryPhonePrefix = {
        v match {
          case 86 => CN
            case 81 => JP
            case 82 => KR
            case 1 => US
            case 44 => UK
            
          case _ => new UserCountryPhonePrefix(v,"#"+ v)
        }
      }

      def apply(v: Int) = findByValue(v)
      def unapply(v: UserCountryPhonePrefix): Option[Int] = Some(v.id)

    }
    