 package com.today36524.api.user.response.serializer;
        import com.today36524.api.common.domain.serializer.*;import com.today36524.api.user.response.serializer.*;import com.today36524.api.user.request.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/
        public class FindUsersByPageResponseSerializer implements BeanSerializer<com.today36524.api.user.response.FindUsersByPageResponse>{
        
      @Override
      public com.today36524.api.user.response.FindUsersByPageResponse read(TProtocol iprot) throws TException{

      com.today36524.api.user.response.FindUsersByPageResponse bean = new com.today36524.api.user.response.FindUsersByPageResponse();
      com.github.dapeng.org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.STRUCT){
              com.today36524.api.common.domain.PageResponse elem0 = new com.today36524.api.common.domain.PageResponse();
        elem0=new com.today36524.api.common.domain.serializer.PageResponseSerializer().read(iprot);
       bean.setPageResponse(elem0);
            }else{
              com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 2:
              if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.LIST){
               com.github.dapeng.org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
        java.util.List<com.today36524.api.user.response.GetUserResponse> elem0 = new java.util.ArrayList<>(_list0.size);
        for(int _i0 = 0; _i0 < _list0.size; ++ _i0){
          com.today36524.api.user.response.GetUserResponse elem1 = new com.today36524.api.user.response.GetUserResponse();
        elem1=new com.today36524.api.user.response.serializer.GetUserResponseSerializer().read(iprot);
          elem0.add(elem1);
        }
        iprot.readListEnd();
       bean.setResults(elem0);
            }else{
              com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.today36524.api.user.response.FindUsersByPageResponse bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new com.github.dapeng.org.apache.thrift.protocol.TStruct("FindUsersByPageResponse"));

      
            oprot.writeFieldBegin(new com.github.dapeng.org.apache.thrift.protocol.TField("pageResponse", com.github.dapeng.org.apache.thrift.protocol.TType.STRUCT, (short) 1));
            com.today36524.api.common.domain.PageResponse elem0 = bean.getPageResponse();
             new com.today36524.api.common.domain.serializer.PageResponseSerializer().write(elem0, oprot);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new com.github.dapeng.org.apache.thrift.protocol.TField("results", com.github.dapeng.org.apache.thrift.protocol.TType.LIST, (short) 2));
            java.util.List<com.today36524.api.user.response.GetUserResponse> elem1 = bean.getResults();
            
          oprot.writeListBegin(new com.github.dapeng.org.apache.thrift.protocol.TList(com.github.dapeng.org.apache.thrift.protocol.TType.STRUCT, elem1.size()));
          for(com.today36524.api.user.response.GetUserResponse elem2 : elem1){
           new com.today36524.api.user.response.serializer.GetUserResponseSerializer().write(elem2, oprot);
        }
          oprot.writeListEnd();
        
            
            oprot.writeFieldEnd();
          
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.today36524.api.user.response.FindUsersByPageResponse bean) throws TException{
      
              if(bean.getPageResponse() == null)
              throw new SoaException(SoaCode.NotNull, "pageResponse字段不允许为空");
            
                if(bean.getPageResponse() != null)
                new com.today36524.api.common.domain.serializer.PageResponseSerializer().validate(bean.getPageResponse());
              
              if(bean.getResults() == null)
              throw new SoaException(SoaCode.NotNull, "results字段不允许为空");
            
    }
    
        @Override
        public String toString(com.today36524.api.user.response.FindUsersByPageResponse bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      