package com.today36524.api.common.domain;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

 鑫知结算币种

        **/
        public enum Currency implements com.github.dapeng.org.apache.thrift.TEnum{
        
            /**
            *

 心点

            **/
            XUEDIAN(1),
          
            /**
            *

 知点

            **/
            JIAODIAN(2);
          

        private final int value;

        private Currency(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static Currency findByValue(int value){
            switch(value){
            
                 case 1:
                    return XUEDIAN;
               
                 case 2:
                    return JIAODIAN;
               
               default:
                   return null;
            }
        }
        }
      