package com.today36524.api.user.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

 积分来源

        **/
        public enum IntegralSourceEnum implements com.github.dapeng.org.apache.thrift.TEnum{
        
            /**
            *

 完善个人资料

            **/
            PREFECT_INFORMATION(1),
          
            /**
            *

 拉黑

            **/
            BLACK(2);
          

        private final int value;

        private IntegralSourceEnum(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static IntegralSourceEnum findByValue(int value){
            switch(value){
            
                 case 1:
                    return PREFECT_INFORMATION;
               
                 case 2:
                    return BLACK;
               
               default:
                   return null;
            }
        }
        }
      