package com.today36524.api.user.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

 会员用户状态（是否可用及会员级别）

        **/
        public enum UserStatusEnum implements com.github.dapeng.org.apache.thrift.TEnum{
        
            /**
            *

 等待激活（预留）

            **/
            ACTIVATING(0),
          
            /**
            *

 已激活

            **/
            ACTIVATED(1),
          
            /**
            *

 权属会员（资料已完善）

            **/
            DATA_PERFECTED(2),
          
            /**
            *

 冻结用户（涉嫌违规处理冻结期）

            **/
            FREEZED(3),
          
            /**
            *

 黑名单用户

            **/
            BLACK(4),
          
            /**
            *

 逻辑删除

            **/
            DELETE(99);
          

        private final int value;

        private UserStatusEnum(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static UserStatusEnum findByValue(int value){
            switch(value){
            
                 case 0:
                    return ACTIVATING;
               
                 case 1:
                    return ACTIVATED;
               
                 case 2:
                    return DATA_PERFECTED;
               
                 case 3:
                    return FREEZED;
               
                 case 4:
                    return BLACK;
               
                 case 99:
                    return DELETE;
               
               default:
                   return null;
            }
        }
        }
      