package com.today36524.api.user.scala.response

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 分页查询用户返回体

        **/
        case class FindUsersByPageResponse(

         /**
        *
        **/
        
        pageResponse : com.today36524.api.common.scala.domain.PageResponse, /**
        *
        **/
        
        results : List[com.today36524.api.user.scala.response.GetUserResponse]
        )
      