package com.today36524.api.user.scala.response

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 获取单个用户返回体

        **/
        case class GetUserResponse(

         /**
        *
        **/
        
        userName : String, /**
        *
        **/
        
        telephone : String, /**
        *
        **/
        
        email : String, /**
        *
        **/
        
        qq : String, /**
        *
        **/
        
        status : com.today36524.api.user.scala.enums.UserStatusEnum, /**
        *
        **/
        
        integral : Int, /**
        *
        **/
        
        createdAt : Long, /**
        *
        **/
        
        updatedAt : Long
        )
      