package com.today36524.api.user.request;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 记录请求流水接口

        **/
        public class ChangeIntegralRequest{
        
            /**
            *

 用户 id

            **/
            public String userId ;
            public String getUserId(){ return this.userId; }
            public void setUserId(String userId){ this.userId = userId; }

            public String userId(){ return this.userId; }
            public ChangeIntegralRequest userId(String userId){ this.userId = userId; return this; }
          
            /**
            *

  该流水涉及到的积分数(可正可负)

            **/
            public String integralPrice ;
            public String getIntegralPrice(){ return this.integralPrice; }
            public void setIntegralPrice(String integralPrice){ this.integralPrice = integralPrice; }

            public String integralPrice(){ return this.integralPrice; }
            public ChangeIntegralRequest integralPrice(String integralPrice){ this.integralPrice = integralPrice; return this; }
          
            /**
            *

  积分流水类型

            **/
            public com.today36524.api.user.enums.IntegralTypeEnum integralType ;
            public com.today36524.api.user.enums.IntegralTypeEnum getIntegralType(){ return this.integralType; }
            public void setIntegralType(com.today36524.api.user.enums.IntegralTypeEnum integralType){ this.integralType = integralType; }

            public com.today36524.api.user.enums.IntegralTypeEnum integralType(){ return this.integralType; }
            public ChangeIntegralRequest integralType(com.today36524.api.user.enums.IntegralTypeEnum integralType){ this.integralType = integralType; return this; }
          
            /**
            *

  积分改变的来源

            **/
            public com.today36524.api.user.enums.IntegralSourceEnum integralSource ;
            public com.today36524.api.user.enums.IntegralSourceEnum getIntegralSource(){ return this.integralSource; }
            public void setIntegralSource(com.today36524.api.user.enums.IntegralSourceEnum integralSource){ this.integralSource = integralSource; }

            public com.today36524.api.user.enums.IntegralSourceEnum integralSource(){ return this.integralSource; }
            public ChangeIntegralRequest integralSource(com.today36524.api.user.enums.IntegralSourceEnum integralSource){ this.integralSource = integralSource; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("userId").append("\":\"").append(this.userId).append("\",");
    stringBuilder.append("\"").append("integralPrice").append("\":\"").append(this.integralPrice).append("\",");
    stringBuilder.append("\"").append("integralType").append("\":").append(this.integralType).append(",");
    stringBuilder.append("\"").append("integralSource").append("\":").append(this.integralSource).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      