package com.today36524.api.user.request;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class FindUsersByPageRequest{
        
            /**
            *
            **/
            public Optional<String> userName = Optional.empty();
            public Optional<String> getUserName(){ return this.userName; }
            public void setUserName(Optional<String> userName){ this.userName = userName; }

            public Optional<String> userName(){ return this.userName; }
            public FindUsersByPageRequest userName(Optional<String> userName){ this.userName = userName; return this; }
          
            /**
            *
            **/
            public Optional<String> telephone = Optional.empty();
            public Optional<String> getTelephone(){ return this.telephone; }
            public void setTelephone(Optional<String> telephone){ this.telephone = telephone; }

            public Optional<String> telephone(){ return this.telephone; }
            public FindUsersByPageRequest telephone(Optional<String> telephone){ this.telephone = telephone; return this; }
          
            /**
            *
            **/
            public Optional<String> email = Optional.empty();
            public Optional<String> getEmail(){ return this.email; }
            public void setEmail(Optional<String> email){ this.email = email; }

            public Optional<String> email(){ return this.email; }
            public FindUsersByPageRequest email(Optional<String> email){ this.email = email; return this; }
          
            /**
            *
            **/
            public Optional<String> qq = Optional.empty();
            public Optional<String> getQq(){ return this.qq; }
            public void setQq(Optional<String> qq){ this.qq = qq; }

            public Optional<String> qq(){ return this.qq; }
            public FindUsersByPageRequest qq(Optional<String> qq){ this.qq = qq; return this; }
          
            /**
            *
            **/
            public Optional<com.today36524.api.user.enums.UserStatusEnum> status = Optional.empty();
            public Optional<com.today36524.api.user.enums.UserStatusEnum> getStatus(){ return this.status; }
            public void setStatus(Optional<com.today36524.api.user.enums.UserStatusEnum> status){ this.status = status; }

            public Optional<com.today36524.api.user.enums.UserStatusEnum> status(){ return this.status; }
            public FindUsersByPageRequest status(Optional<com.today36524.api.user.enums.UserStatusEnum> status){ this.status = status; return this; }
          
            /**
            *

 bg代表起始日期，ed代表结束日期

            **/
            public Optional<String> createdAtBg = Optional.empty();
            public Optional<String> getCreatedAtBg(){ return this.createdAtBg; }
            public void setCreatedAtBg(Optional<String> createdAtBg){ this.createdAtBg = createdAtBg; }

            public Optional<String> createdAtBg(){ return this.createdAtBg; }
            public FindUsersByPageRequest createdAtBg(Optional<String> createdAtBg){ this.createdAtBg = createdAtBg; return this; }
          
            /**
            *
            **/
            public Optional<String> createdAtEd = Optional.empty();
            public Optional<String> getCreatedAtEd(){ return this.createdAtEd; }
            public void setCreatedAtEd(Optional<String> createdAtEd){ this.createdAtEd = createdAtEd; }

            public Optional<String> createdAtEd(){ return this.createdAtEd; }
            public FindUsersByPageRequest createdAtEd(Optional<String> createdAtEd){ this.createdAtEd = createdAtEd; return this; }
          
            /**
            *
            **/
            public Optional<String> updatedByBg = Optional.empty();
            public Optional<String> getUpdatedByBg(){ return this.updatedByBg; }
            public void setUpdatedByBg(Optional<String> updatedByBg){ this.updatedByBg = updatedByBg; }

            public Optional<String> updatedByBg(){ return this.updatedByBg; }
            public FindUsersByPageRequest updatedByBg(Optional<String> updatedByBg){ this.updatedByBg = updatedByBg; return this; }
          
            /**
            *
            **/
            public Optional<String> updatedByEd = Optional.empty();
            public Optional<String> getUpdatedByEd(){ return this.updatedByEd; }
            public void setUpdatedByEd(Optional<String> updatedByEd){ this.updatedByEd = updatedByEd; }

            public Optional<String> updatedByEd(){ return this.updatedByEd; }
            public FindUsersByPageRequest updatedByEd(Optional<String> updatedByEd){ this.updatedByEd = updatedByEd; return this; }
          
            /**
            *

 分页参数

            **/
            public com.today36524.api.common.domain.PageRequest pageRequest ;
            public com.today36524.api.common.domain.PageRequest getPageRequest(){ return this.pageRequest; }
            public void setPageRequest(com.today36524.api.common.domain.PageRequest pageRequest){ this.pageRequest = pageRequest; }

            public com.today36524.api.common.domain.PageRequest pageRequest(){ return this.pageRequest; }
            public FindUsersByPageRequest pageRequest(com.today36524.api.common.domain.PageRequest pageRequest){ this.pageRequest = pageRequest; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("userName").append("\":\"").append(this.userName.isPresent()?this.userName.get():null).append("\",");
    stringBuilder.append("\"").append("telephone").append("\":\"").append(this.telephone.isPresent()?this.telephone.get():null).append("\",");
    stringBuilder.append("\"").append("email").append("\":\"").append(this.email.isPresent()?this.email.get():null).append("\",");
    stringBuilder.append("\"").append("qq").append("\":\"").append(this.qq.isPresent()?this.qq.get():null).append("\",");
    stringBuilder.append("\"").append("status").append("\":").append(this.status.isPresent()?this.status.get():null).append(",");
    stringBuilder.append("\"").append("createdAtBg").append("\":\"").append(this.createdAtBg.isPresent()?this.createdAtBg.get():null).append("\",");
    stringBuilder.append("\"").append("createdAtEd").append("\":\"").append(this.createdAtEd.isPresent()?this.createdAtEd.get():null).append("\",");
    stringBuilder.append("\"").append("updatedByBg").append("\":\"").append(this.updatedByBg.isPresent()?this.updatedByBg.get():null).append("\",");
    stringBuilder.append("\"").append("updatedByEd").append("\":\"").append(this.updatedByEd.isPresent()?this.updatedByEd.get():null).append("\",");
    stringBuilder.append("\"").append("pageRequest").append("\":").append(this.pageRequest.toString()).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      