package com.today36524.api.user.request;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 获取单个用户请求体（默认用id获取用户）

        **/
        public class GetUserRequest{
        
            /**
            *

 用户id

            **/
            public String id ;
            public String getId(){ return this.id; }
            public void setId(String id){ this.id = id; }

            public String id(){ return this.id; }
            public GetUserRequest id(String id){ this.id = id; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":\"").append(this.id).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      