 package com.today36524.api.user.request.serializer;
        import com.today36524.api.common.domain.serializer.*;import com.today36524.api.user.response.serializer.*;import com.today36524.api.user.request.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/
        public class ChangeIntegralRequestSerializer implements BeanSerializer<com.today36524.api.user.request.ChangeIntegralRequest>{
        
      @Override
      public com.today36524.api.user.request.ChangeIntegralRequest read(TProtocol iprot) throws TException{

      com.today36524.api.user.request.ChangeIntegralRequest bean = new com.today36524.api.user.request.ChangeIntegralRequest();
      com.github.dapeng.org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.STRING){
              String elem0 = iprot.readString();
       bean.setUserId(elem0);
            }else{
              com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 2:
              if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.STRING){
              String elem0 = iprot.readString();
       bean.setIntegralPrice(elem0);
            }else{
              com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 3:
              if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.I32){
              com.today36524.api.user.enums.IntegralTypeEnum elem0 = com.today36524.api.user.enums.IntegralTypeEnum.findByValue(iprot.readI32());
       bean.setIntegralType(elem0);
            }else{
              com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 4:
              if(schemeField.type == com.github.dapeng.org.apache.thrift.protocol.TType.I32){
              com.today36524.api.user.enums.IntegralSourceEnum elem0 = com.today36524.api.user.enums.IntegralSourceEnum.findByValue(iprot.readI32());
       bean.setIntegralSource(elem0);
            }else{
              com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            com.github.dapeng.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.today36524.api.user.request.ChangeIntegralRequest bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new com.github.dapeng.org.apache.thrift.protocol.TStruct("ChangeIntegralRequest"));

      
            oprot.writeFieldBegin(new com.github.dapeng.org.apache.thrift.protocol.TField("userId", com.github.dapeng.org.apache.thrift.protocol.TType.STRING, (short) 1));
            String elem0 = bean.getUserId();
            oprot.writeString(elem0);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new com.github.dapeng.org.apache.thrift.protocol.TField("integralPrice", com.github.dapeng.org.apache.thrift.protocol.TType.STRING, (short) 2));
            String elem1 = bean.getIntegralPrice();
            oprot.writeString(elem1);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new com.github.dapeng.org.apache.thrift.protocol.TField("integralType", com.github.dapeng.org.apache.thrift.protocol.TType.I32, (short) 3));
            com.today36524.api.user.enums.IntegralTypeEnum elem2 = bean.getIntegralType();
            oprot.writeI32(elem2.getValue());
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new com.github.dapeng.org.apache.thrift.protocol.TField("integralSource", com.github.dapeng.org.apache.thrift.protocol.TType.I32, (short) 4));
            com.today36524.api.user.enums.IntegralSourceEnum elem3 = bean.getIntegralSource();
            oprot.writeI32(elem3.getValue());
            
            oprot.writeFieldEnd();
          
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.today36524.api.user.request.ChangeIntegralRequest bean) throws TException{
      
              if(bean.getUserId() == null)
              throw new SoaException(SoaCode.NotNull, "userId字段不允许为空");
            
              if(bean.getIntegralPrice() == null)
              throw new SoaException(SoaCode.NotNull, "integralPrice字段不允许为空");
            
              if(bean.getIntegralType() == null)
              throw new SoaException(SoaCode.NotNull, "integralType字段不允许为空");
            
              if(bean.getIntegralSource() == null)
              throw new SoaException(SoaCode.NotNull, "integralSource字段不允许为空");
            
    }
    
        @Override
        public String toString(com.today36524.api.user.request.ChangeIntegralRequest bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      