package com.today36524.api.user.scala.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class FindUsersByPageRequest(

         /**
        *

 分页参数

        **/
        
        pageRequest : com.today36524.api.common.scala.domain.PageRequest, /**
        *
        **/
        
        userName : Option[String] = None, /**
        *
        **/
        
        telephone : Option[String] = None, /**
        *
        **/
        
        email : Option[String] = None, /**
        *
        **/
        
        qq : Option[String] = None, /**
        *
        **/
        
        status : Option[com.today36524.api.user.scala.enums.UserStatusEnum] = None, /**
        *

 bg代表起始日期，ed代表结束日期

        **/
        
        createdAtBg : Option[String] = None, /**
        *
        **/
        
        createdAtEd : Option[String] = None, /**
        *
        **/
        
        updatedByBg : Option[String] = None, /**
        *
        **/
        
        updatedByEd : Option[String] = None
        )
      