package com.today36524.api.user.scala.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 手机号获取单个用户请求体

        **/
        case class GetUserByTelephoneRequest(

         /**
        *

 用户手机号

        **/
        
        telephone : String
        )
      