package com.today36524.api.user.scala.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 获取单个用户请求体（默认用id获取用户）

        **/
        case class GetUserRequest(

         /**
        *

 用户id

        **/
        
        id : String
        )
      