package com.today36524.api.user.scala.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 修改用户请求体(初始化修改时必填[积分相关]，之后修改选填)

        **/
        case class ModifyUserRequest(

         /**
        *

 用户邮箱

        **/
        
        email : String, /**
        *

 用户 qq

        **/
        
        qq : String, /**
        *

 用户 id

        **/
        
        userId : String
        )
      