package com.today36524.api.user.scala.request

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 解冻操作请求体

        **/
        case class UnfreezeUserRequest(

         /**
        *

 用户 id

        **/
        
        userId : String, /**
        *

  操作员解冻备注

        **/
        
        remark : String
        )
      